/*
 * CREATING TABLES
 */
CREATE TABLE APP_USER(
	USER_ID NUMBER(9) PRIMARY KEY,
	USER_TYPE VARCHAR2(10),
	FIRST_NAME VARCHAR2(100) NOT NULL,
	lAST_NAME VARCHAR2(100) NOT NULL,
	EMAIL VARCHAR2(100) UNIQUE
);

CREATE TABLE REQUEST(
	REQUEST_ID NUMBER(9) PRIMARY KEY, -- THIS IS EQUIVALENT TO SETTING A UNIQUE AND NON NULL CONSTRAINT ON THIS COLUMN
	USER_ID NUMBER(9) REFERENCES APP_USER,
	STATUS VARCHAR2(10) NOT NULL,
	AMOUNT NUMBER(10,2), -- 99999999.99
	REASON VARCHAR2(100)
);


ALTER TABLE APP_USER 
ADD PASSWORD VARCHAR2(20) NOT NULL

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD)  VALUES (1,'CUSTOMER','Kevin','Gilliam','kevgill@gmail.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES(2,'CUSTOMER','Sean','Andrew','andy123@gmail.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES (3,'CUSTOMER','John','Jacobson','jj321@gmail.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES (4,'EMPLOYEE','Kelly','Johnson','Kelly.Johnson@bankapp.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES (5,'EMPLOYEE','Albert','Ferrero','albert.ferrero@bankapp.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD) VALUES (6,'MANAGER','Anthony','Smith','anthony.smith@bankapp.com','password');

INSERT INTO APP_USER (USER_ID,USER_TYPE,FIRST_NAME,LAST_NAME,EMAIL,PASSWORD)  VALUES (9,'CUSTOMER','Test','User','test3@gmail.com','password');

SELECT * FROM APP_USER

SELECT * FROM REQUEST; 

CREATE SEQUENCE SQ_REQUEST_PK
START WITH 1
INCREMENT BY 1;

CREATE OR REPLACE TRIGGER TR_INSERT_REQUEST_PK
BEFORE INSERT ON REQUEST
FOR EACH ROW 
BEGIN 
	SELECT SQ_REQUEST_PK.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
END;
/


ALTER TABLE REQUEST ADD EMAIL VARCHAR2(100);

ALTER TABLE REQUEST DROP COLUMN USER_ID;

UPDATE APP_USER SET USER_TYPE = 'MANAGER' WHERE USER_ID = 6

UPDATE APP_USER SET USER_TYPE = 'EMPLOYEE' WHERE USER_TYPE = 'MANAGER'

ALTER TABLE REQUEST ADD DATE_CREATED VARCHAR2(20);

ALTER TABLE REQUEST ADD USER_ID NUMBER(9) REFERENCES APP_USER;